name: Python CI Pipeline

on:
  push:
    branches:
      - main  # Triggers on push to main branch
  pull_request:
    branches:
      - main  # Triggers on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Environment to run the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .  # Lint all Python files in the repository

      - name: Run tests
        run: |
          pip install pytest
          pytest  # Run tests using pytest
