name: Node.js CI

on:
  push:
    branches:
      - main  # Run tests on push to the main branch
  pull_request:
    branches:
      - main  # Run tests when there's a pull request to main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]  # Define Node.js versions to test against

    steps:
    - uses: actions/checkout@v2  # Checkout code
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install  # Install dependencies
    - run: npm test     # Run tests (you should define tests in package.json)
name: Node.js CI/CD

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm test

  deploy:
    needs: build  # Run this job only if the build (tests) succeeds
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
