name: Python CI Pipeline

# Define when the pipeline should run (e.g., on push or pull request)
on:
  push:
    branches:
      - main  # Runs when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Runs when a PR is created targeting 'main' branch

# Define jobs (tasks) in the pipeline
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Lint the code (Optional)
      - name: Lint with flake8
        run: |
          pip install flake8
          # Ignore certain errors or warnings, adjust based on your needs
          flake8 --max-line-length=88 --ignore=E203,W503 .

      # Step 5: Run the tests
      - name: Run tests
        run: |
          pytest  # Run the tests using pytest
