name: Node.js CI

on:
  push:
    branches:
      - main  # Run tests on push to the main branch
  pull_request:
    branches:
      - main  # Run tests when there's a pull request to main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]  # Define Node.js versions to test against

    steps:
    - uses: actions/checkout@v2  # Checkout code
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install  # Install dependencies
    - run: npm test     # Run tests (you should define tests in package.json)
